siteTitle = "Rhostem's note"
siteDescr = "blog powered by Gatsby"
siteAuthor = "rhostem"

siteGithubUrl = "https://github.com/rhostem"
siteEmailUrl = "syoung.j@gmail.com"
siteRssUrl = "#"
siteTwitterUrl = "#"

googleAnalyticsId = "UA-83587837-3"

linkPrefix = "/blog"
cdn = "https://s3.ap-northeast-2.amazonaws.com/rhostem-cdn"
