siteTitle = "rhostem's note"
siteDescr = "blog powered by Gatsby"
siteAuthor = "rhostem"

siteGithubUrl = "https://github.com/rhostem"
siteEmailUrl = "syoung.j@gmail.com"
siteRssUrl = "#"
siteTwitterUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/blog"